# Generated by Django 3.1.5 on 2021-01-11 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('manu_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exp_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('no_boxes_received', models.IntegerField(blank=True, null=True)),
                ('no_units_in_box', models.IntegerField(blank=True, null=True)),
                ('no_units_dispatched', models.IntegerField(blank=True, null=True)),
                ('no_units_left', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
