# Generated by Django 3.1.5 on 2021-01-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='item_type',
        ),
    ]
