# Generated by Django 3.1.5 on 2021-01-11 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stock_system.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock_system', '0002_auto_20210111_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('item', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='manu_date',
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(default=stock_system.models.generate, editable=False, max_length=100, unique=True)),
                ('boxes_received', models.IntegerField(blank=True, null=True)),
                ('units_per_box', models.IntegerField(blank=True, null=True)),
                ('man_date', models.DateTimeField(blank=True, null=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_brand', to='stock_system.brand')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ManyToManyField(blank=True, related_name='stocks', to='stock_system.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batch', to='stock_system.batch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_brand', to='stock_system.brand'),
        ),
    ]
