# Generated by Django 3.1.5 on 2021-01-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0003_auto_20210111_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='no_boxes_received',
            new_name='no_units',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='no_units_in_box',
        ),
    ]
