# Generated by Django 3.1.5 on 2021-01-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0004_auto_20210111_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='brand',
        ),
        migrations.AddField(
            model_name='batch',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='batch_brands', to='stock_system.Brand'),
        ),
    ]
