# Generated by Django 3.1.5 on 2021-01-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0011_auto_20210128_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchid',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='brands', to='stock_system.Brand'),
        ),
    ]
