# Generated by Django 3.1.5 on 2021-01-29 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0012_batchid_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchitems',
            old_name='batch_id',
            new_name='batch',
        ),
    ]
