# Generated by Django 3.1.5 on 2021-01-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0014_batchid_batch_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchitems',
            name='brand',
        ),
        migrations.AddField(
            model_name='batchitems',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='batch_brand', to='stock_system.Brand'),
        ),
    ]
