# Generated by Django 3.1.5 on 2021-01-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0015_auto_20210130_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchid',
            name='brand',
        ),
    ]
