# Generated by Django 3.1.5 on 2021-02-01 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0018_auto_20210201_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='brand',
        ),
        migrations.AddField(
            model_name='stock',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_brand', to='stock_system.brand'),
        ),
    ]
