# Generated by Django 3.1.5 on 2021-02-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0020_auto_20210201_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='stock',
            field=models.ManyToManyField(blank=True, related_name='brand_stocks', to='stock_system.Stock'),
        ),
    ]
