# Generated by Django 3.1.5 on 2021-02-18 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0025_auto_20210203_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('date_returned', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_returns', to='stock_system.brand')),
            ],
        ),
    ]
