# Generated by Django 3.1.5 on 2021-02-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0026_returns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returns',
            options={'ordering': ('-date_returned',)},
        ),
        migrations.AddField(
            model_name='batchid',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
