# Generated by Django 3.1.5 on 2021-02-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0027_auto_20210219_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchid',
            name='request_del',
            field=models.BooleanField(default=False),
        ),
    ]
