# Generated by Django 3.1.7 on 2021-02-21 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0029_returns_received_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatched',
            options={'ordering': ('-date_dispatched',)},
        ),
        migrations.RemoveField(
            model_name='returns',
            name='brand',
        ),
        migrations.AddField(
            model_name='returns',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_returns', to='stock_system.stock'),
        ),
        migrations.AlterField(
            model_name='returns',
            name='reason',
            field=models.CharField(blank=True, choices=[('Unwanted', 'Unwanted'), ('Expired', 'Expired'), ('Damaged', 'Damaged')], max_length=250, null=True),
        ),
    ]
