# Generated by Django 3.1.7 on 2021-02-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0030_auto_20210221_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='pack_type',
            field=models.CharField(blank=True, choices=[('Carton', 'Carton'), ('Box', 'Box')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='returns',
            name='reason',
            field=models.CharField(blank=True, choices=[('Expired', 'Expired'), ('Damaged', 'Damaged'), ('Unwanted', 'Unwanted')], max_length=250, null=True),
        ),
    ]
