# Generated by Django 3.1.7 on 2021-02-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0031_auto_20210221_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='pack_type',
        ),
    ]
