# Generated by Django 3.1.7 on 2021-02-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0032_remove_brand_pack_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='batch_item',
        ),
        migrations.AddField(
            model_name='stock',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_brand', to='stock_system.brand'),
        ),
        migrations.AlterField(
            model_name='returns',
            name='reason',
            field=models.CharField(blank=True, choices=[('Unwanted', 'Unwanted'), ('Damaged', 'Damaged'), ('Expired', 'Expired')], max_length=250, null=True),
        ),
    ]
