# Generated by Django 3.1.7 on 2021-02-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0033_auto_20210223_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='no_available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='no_units_dispatched',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='no_units_left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='returns',
            name='reason',
            field=models.CharField(blank=True, choices=[('Damaged', 'Damaged'), ('Unwanted', 'Unwanted'), ('Expired', 'Expired')], max_length=250, null=True),
        ),
    ]
