# Generated by Django 3.1.7 on 2021-02-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0034_auto_20210223_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatched',
            name='stock',
        ),
        migrations.AddField(
            model_name='brand',
            name='dispatches',
            field=models.ManyToManyField(blank=True, related_name='brand_dispatches', to='stock_system.Dispatched'),
        ),
        migrations.AddField(
            model_name='dispatched',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_dispatches', to='stock_system.brand'),
        ),
    ]
