# Generated by Django 3.1.7 on 2021-02-23 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0037_auto_20210224_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitems',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='returns',
            name='reason',
            field=models.CharField(blank=True, choices=[('Damaged', 'Damaged'), ('Unwanted', 'Unwanted'), ('Expired', 'Expired')], max_length=250, null=True),
        ),
    ]
