# Generated by Django 3.1.7 on 2021-02-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_system', '0038_auto_20210224_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_owner', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_company', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='returns',
            name='reason',
            field=models.CharField(blank=True, choices=[('Unwanted', 'Unwanted'), ('Expired', 'Expired'), ('Damaged', 'Damaged')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='batchid',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_batches', to='stock_system.client'),
        ),
        migrations.AddField(
            model_name='brand',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='clients_brands', to='stock_system.Client'),
        ),
    ]
